baseurl = "/"
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-theme"
title = "Puckerbrush Bar & Grill"
[params]
description = "A restaurant and tiki bar in Greenville, Maine."
favicon = "favicon.ico"
name = "Puckerbrush Bar & Grill"
[params.about]
buttontext = "View the menu"
description = "David and Robyn Clark purchased the property in the fall of 2014. They were frequent visitors to the former restaurant (The Black Frog) and own a home in the area.  They have always had a dream of owning a restaurant as they love to feed, entertain and enjoy time with family and friends.<br /><br />David worked 40 years at Bath Iron Works.  After retiring from BIW in 2014, he has continued his shipbuilding career as a Consultant while pursuing his dream of owning a restaurant.  Robyn has worked 26 years in the banking industry in Finance and is a graduate of Robert Morris University with a Bachelor’s Degree in Finance.  She shares David’s dream of owning a restaurant and is now committing 100% of her time in helping this dream come alive.<br /><br />Both David and Robyn have completed the State Certified Course in Restaurant Food Safety (ServSafe), have a strong work ethic and a passion for entertainment and ensuring guests eat well and enjoy."
headline = "Fine food and fun!"
[params.aside]
headline = "Visit our Facebook page for more information"
[params.aside.button]
link = "//facebook.com/pg/Puckerbrush-Bar-Grill-1501898703429971"
text = "Go now"
[params.contact]
description = "Still have questions? Here's how to reach us!"
email = "robyn@puckerbrush.com"
headline = "Let's Get In Touch!"
phone = "123-456-6789"
[params.hero]
buttontext = "About Us"
slogan = "FIRED UP"
subtitle = "[We're getting the grill hot!<br /> Keep an eye on our Facebook page for updates.](//facebook.com/pg/Puckerbrush-Bar-Grill-1501898703429971)"
[params.location]
latitude = "45.4592694"
longitude = "-69.5947636"
maps_api_key = "AIzaSyAnnVX70erU2KOMTFIgZCUWike1HrDtuWQ"
[params.navigation]
brand = "Puckerbrush Bar & Grill"
[params.navigation.links]
about = "About"
contact = "Contact"
portfolio = "Gallery"
services = "Menu"
[params.portfolio]
headline = "Our menu is fresh and hot off the grill"
[params.portfolio.modal]
buttontext = "Close"
category = "Category"
client = "Client"
date = "Date"
[params.services]
headline = "Our menu is as fresh as the ingredients we use."
[[params.services.list]]
description = "Our templates are updated regularly so they don't break."
icon = "fa-diamond"
title = "Appetizers"
[[params.services.list]]
description = "You can use this theme as is, or you can make changes!"
icon = "fa-paper-plane"
title = "Sandwiches"
[[params.services.list]]
description = "We update dependencies to keep things fresh."
icon = "fa-newspaper-o"
title = "Entrees"
[[params.services.list]]
description = "You have to make your websites with love these days!"
icon = "fa-heart"
title = "Desserts"
